### ISSUE TITLE
Hyphenating only words which are longer than the block element width

### ISSUE THREAD

**Issue by ciembor** [mnater/Hyphenator#219]
Maybe I missed something in documentation, but I have a German text and I would like to hyphenate only words which are too long to fit in a block element. Hyphenator by default hyphenates also other words, which could be moved to the new line. Is this feature implemented? If not, treat this as a feature request :).

**Comment by mnater** [comment]
Hi

No, this isn't implemented. And I don't see how this could be achieved: AFAIK, there's no way to reliably know if a word is too long nor if it is at the end of a line. (Yes, we could wrap each word in a span but that's a lot of work in the DOM and thus not very performant.)
Therefor Hyphenator just hyphenates all words (also this becomes very useful when a user resizes the text of the window).

Regards, Mathias
