### ISSUE TITLE
Error on Hyphenator.run()

### ISSUE THREAD

**Issue by davidmalavasi** [mnater/Hyphenator#223]
Hi, sobald ich Hyphenator.run() im Code hinzufüge, bekomme ich in Internet Explorer und Opera folgende Fehlermeldung, sobald die Seite geladen wird: "Hyphenator.js says: An Error occured: Cannot read property 'length' of undefined"

In Chrome scheint es interessanterweise aber zu funktionieren. Firefox kann ich momentan nicht testen.

Hier der Code, den ich in Drupal direkt in meinem Inhalt platziere:

<script src="/sites/all/themes/my-theme/js/Hyphenator-master/Hyphenator.js" type="text/javascript"></script>
        <script src="/sites/all/themes/my-theme/js/Hyphenator-master/patterns/de.js" type="text/javascript"></script>
        <script type="text/javascript">
                Hyphenator.config({
                    displaytogglebox : true,
                    minwordlength : 4
                });
                Hyphenator.run();
        </script>

Ich vermute mal, dass sicher der Error auf Zeile 3062 in Hyphenator.js bezieht, aber wie könnte ich das lösen?

Vielen Dank im voraus.

**Comment by mnater** [comment]
Hallo

Kannst du mir die ganze HTML-Seite zeigen, bei der der Fehler auftritt?
Um welche IE- und Opera-Versionen handelt es sich?

Hyphenator.run() ruft die interne Funktion runWhenLoaded() auf, die ihrerseits ein Polyfill für den DOMContentLoaded-Event darstellt. Da scheint es irgendein Durcheinander zu geben und um das zu debuggen brauche ich eine komplette HTML-Seite…

**Comment by davidmalavasi** [comment]
Hi Mathias, ich hab jetzt den bramstein hypher verwendet https://github.com/bramstein/hypher

Ich müsste das ganze nochmal nachbauen. Sobald ich dazu komme melde ich mich wieder.

**Comment by mnater** [comment]
OK, wenn du auch jQuery einsetzt, ist hypher eine sehr gute Alternative. Ich schliesse dieses Issue hier einfach mal (solange).

**Comment by davidmalavasi** [comment]
Hi Mathias!

Ich habe jetzt nochmal die Hyphenator Library ausprobiert und siehe da: alles funktioniert.
Was mir soeben auffällt: In dem Beitrag, den ich gepostet habe, habe ich ja die "patterns/de.js" eingebunden.

Jetzt wo es funktioniert habe ich "Hyphenator.js" eingebunden.

<script src="/sites/all/themes/my-theme/js/Hyphenator/Hyphenator.js" type="text/javascript"></script>
        <script type="text/javascript">
            Hyphenator.config({
                displaytogglebox : true,
                minwordlength : 4
            });
            Hyphenator.run();
        </script>

Ich weiß nicht mal mehr, warum ich das zuvor wie im obigen Code eingebettet habe.
Aber wie gesagt: so funktionierts.
