### ISSUE TITLE
Run Hyphenator.hypenate on AJAX returned data

### ISSUE THREAD

**Issue by fidoboy** [mnater/Hyphenator#224]
Hi, I'm trying to hyphenate ONLY the data returned from AJAX call before adding it to my DOM. This data is, obviously, a HTML string, so if i call `Hyphenator.hyphenate` on this string the HTML is destroyed. How can I use Hyphenator with my AJAX call avoiding to use the run method again over all the document?? I've tried to locate any documentation about this issue but there is not anything. I've located a few issues here on Github, but not very explained or detailed.

Many thanks in advance, :wink:

**Comment by mnater** [comment]
Hi

Thanks for the interesting request.
Can you provide some code to show what you did?

Also, see http://mnater.github.io/Hyphenator/testsuite/test56.html
Here the HTML string is injected and then hyphenated, which works quite well…
