### ISSUE TITLE
Fails for the long word pneumonoultramicroscopicsilicovolcanoconiosis

### ISSUE THREAD

**Issue by yurivict** [mnater/Hyphenator#226]
It splits its end into one-letter syllables, and puts the first 'p' into the separate syllable:
p-neu-mo-noul-tra-mi-cro-scop-ic-sil-i-cov-o-l-c-a-n-o-c-o-n-i-o-s-i-s

https://en.wikipedia.org/wiki/Longest_word_in_English

I think the former problem is the result of 32-integer limit of wwhpStore:
````
r = new window.Uint8Array(32);
````

The latter problem seems to be an unrelated bug: p-neu-mio-ni-a is wrong. Merriam-Webster gives pneu·mo·nia syllables split: http://www.merriam-webster.com/dictionary/pneumonia

**Comment by mnater** [comment]
Hi

By using a bigger value in wwhpStore (as you correctly worked out) and wwAsMappedCharCodeStore the word gets hyphenated like this in my test:
pneu·mo·noul·tra·mi·cro·scop·ic·sil·i·co·vol·canoco·nio·sis

http://www.merriam-webster.com/medical/pneumonoultramicroscopicsilicovolcanoconiosis hyphenates
pneu·mo·no·ul·tra·mi·cro·scop·ic·sil·i·co·vol·ca·no·co·ni·o·sis

So, besides some hyphenation points that are missed (and that's ok for such a long word) the word is hyphenated correctly by the patterns.
I don't know where the hyphenation point after the first p comes from. May be the language isn't correctly set in your test?

Anyway I'll increase the values from 32 to 64.

**Comment by yurivict** [comment]
I adjusted leftmin=0 and rightmin=0 to see how the word is split into syllables, and got p·neu·mo·nia

This means that syllable splitting algorithm is wrong.
Language is set as "en"
