### ISSUE TITLE
user Hyphenator with node.js

### ISSUE THREAD

**Issue by jobe451** [mnater/Hyphenator#229]
Is it possible to use Hyphenator server side on node.js. I could think of feeding a dom to Hyphenator a DOM object (generated by cheerio or htmlparser2 for instance). 

I would use it to prepare an HTML that is than forwarded to wkhtmltopdf for converting it to PDF.

**Comment by mnater** [comment]
Hi

Hyphenator.js is primarily made for the browser (there's a lot of DOM handling). But it's all Javascript, so basically it would run in Node.js after some modifications. I'm currently not planning to create such a node.js module.

Do you know https://github.com/bramstein/hypher ? This could match your needs.

Regards, Mathias

**Comment by faiwer** [comment]
@jobe451 , You can use Hyphenator on nodejs like this: 
```js
let win =
	{
		location: { href: '' },
		navigator: { userAgent: '' },
		document: { getElementsByTagName: _.constant([]), },
	};
win.window = win;

vm.createContext(win);
let code = require('fs').readFileSync(__dirname +  '/hyphenator.js');
vm.runInContext(code, win);
let Hyphenator = win.Hyphenator;
```
