### ISSUE TITLE
How to break/wrap lines

### ISSUE THREAD

**Issue by iotaweb** [mnater/Hyphenator#230]
This is not an issue as such, more of a use-case looking for a potential solution. 

I'm building an application with Hyphenator that needs to break hyphenated content by line. Effectively, I want to chop hyphenated content up into any number of arbitrary blocks, e.g. to display across multiple panels or to allow for the insertion of images. These breaks in the flow might occur anywhere with in the hyphenated text, e.g. in the middle of a paragraph or list.

So far, I've tried to use Hyphenator in conjunction with libraries that provide this line splitting capability, e.g. https://greensock.com/splittext-example, but unfortunately, this breaks the hyphenation.

So my question is, do you have any ideas of how to solve this problem or any approaches you could suggest?

Regards, Rob

P.S. many thanks for your work on this library - it is brilliant!

**Comment by mnater** [comment]
Hi

I didn't study the code of greensocks splittext, but judging from the example the words or characters or lines are all wrapped in their own div. The browser then renders each div separately as inline-block.

Now hyphenation (be it by CSS or by Hyphenator) only occurs, when a text element spans over multiple lines and the last word on a line doesn't fit the box. The divs produced by splittext are all single-lined, so the browsers layout engine doesn't see any necessity to hyphenate.

I fear the concept of splittext and hyphenation are a bad match and honestly I don't have a solution for this.

(In my opinion the whole concept of splitting text in divs or spans is awkward.)

**Comment by iotaweb** [comment]
Thanks Mathias, I appreciate your thoughts on this and suspected it might not be trivial. I do have a workaround, it just involves a lot of duplicated DOM elements and positioning. If I come a cross a better way, I'll let you know.
