### ISSUE TITLE
Loader does not fire

### ISSUE THREAD

**Issue by rarila** [mnater/Hyphenator#231]
I have tested with three browser that don't support css hyphenation (Chrome 44, IE 9, Opera 31 – Windows 7) and none of them loaded the Hyphenator. So I did some investigation and found that the problem is [that line](https://github.com/mnater/Hyphenator/blob/master/Hyphenator_Loader.js#L113).

All these three browsers return a ``shadow.offsetHeight`` of ``18``instead of the expected ``12``. As soon as I change/add this value everything works as expected. So what could be wrong here?

_PS: The IE8 emulation returns the expected ``12``._

**Comment by mnater** [comment]
Hi

Thanks for that issue and for fixing it.
There are other styling, too that have to be resetted.
I hope this will do the trick.

Regards, Mathias
