### ISSUE TITLE
Run Hyphenator on certain elements after ajax 

### ISSUE THREAD

**Issue by yvanavermaet** [mnater/Hyphenator#233]
Hi

I'm experiencing a problem with Hyphenator and an ajax request.

Situation:
- Hyphenator runs on page load (after calling Hyphenator:run) and it'll check for elements with a certain className.
- An ajax request is triggered (infinite scroll) which loads new content. Javascript will "scrape" what it needs from the response (unfortunately nothing I can change...)
- Calling Hyphenator:run will re-run over the entire document (performance-wise not a good option).
- Calling Hyphenator:hyphenate could run over the newly loaded content (before "scrape"), but it doesn't check for the certain className. This leads to other text being hyphenated, which I don't want)
- Calling Hyphenator:hyphenate can't run over "scraped" elements, because it'll loop over the childnodes, but the scraped elements don't have any childnodes (it's like an Array).

Imo Hyphenator:hyphenate should check for the certain className. It should react the same as the ":run" function.

Kind regards,
Yannick

**Comment by mnater** [comment]
Hi

Interesting use case.
I see an other option:

1. Construct the HTML-nodes tree from the scraped content.
2. Get the elements you want to hyphenate with `rootElement.getElementsByClassName(names);`
3. Hyphenate them with Hyphenator.hyphenate
4. Attach the tree to the document.

I think that's how it should be done. Would this be an option for you?

**Comment by yvanavermaet** [comment]
Hi mnater

Well, that'd imply that I recreate a HTML tree based on the scraped elements, which is "a lot" of overhead + performant-wise not the most ideal solution.

The most performant solution I've found so far, is looping over the scraped elements, check for ".hyphenate"-elements and then loop over those elements and call Hyphenate:hyphenate per element. This is far from ideal, but does the trick.

If only Hyphernate:hyphernate would work the same as Hyphernate:run, but instead of checking the entire document, it would check the passed HTML-node (in my case the entire Ajax Response).

Thanks for your reply btw!

Kind regards,
Yannick

**Comment by mnater** [comment]
Hi Yannick

Yes, sooner or later this tree has to be built. At the latest, when the content is attached to the DOM.

From the AJAX request basically we get some response text. With this text we could either do some fancy regex-stuff or parse it and get some HTML-nodes from it. Since the response text has to be parsed anyway before being attached to the DOM I'd opt for the second option. That gives us the full DOM API over the response text. So we can get the elements that we want to hyphenate.

I don't see any faster way to do this. If I'd implement Hyphenator.hyphenate in a way that it behaves like Hyphenator.run I'd have to do the parsing, too.

Here's a quick and (very) dirty test-case how it can be achieved with the current version of Hyphenator.js:
```html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>InfiniScroll</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">

    <script type="text/javascript" src="hyphenator.js"></script>

    <script type="text/javascript">
        window.onscroll = function () {
            if (window.scrollY >= document.body.offsetHeight - window.innerHeight) {
                var xhr = new XMLHttpRequest();
                xhr.addEventListener('load', function() {
                    //create an element, not yet attached to the document
                    var newDiv = document.createElement('div');
                    //parse the response -> new nodes tree
                    newDiv.innerHTML = this.responseText;
                    //do hyphenation only on elements that have class hyphenate
                    var elToHn = newDiv.getElementsByClassName('hyphenate');
                    for (var i = 0; i < elToHn.length; i += 1) {
                        elToHn[i] = Hyphenator.hyphenate(elToHn[i], "en");
                    }
                    //attach the previously created tree to the document -> layout
                    document.getElementById("wrapper").appendChild(newDiv);
                });
                xhr.open("get", 'loadmore.php', true);
                xhr.send();
            }
        };
    </script>

    <style>
        body {margin:0px;}
        #wrapper {
            width: 200px;
            margin: auto;
        }
        p {text-align: justify;}
    </style>
</head>
<body>
    <div id="wrapper">
        <div class="loadwrapper">
        <?php include('loadmore.php'); ?>
        </div>
    </div>
</body>
</html>
```

Or, maybe I completely misunderstood something here…

Kind regards,
Mathias

**Comment by yvanavermaet** [comment]
Hi Mathias

Thanks for the example.
There is a small difference that in the responseText, we have to scrape some <li>-elements which are then appended to an existing <ol>-element.
It does give me an idea on how to approach my situation:
I could create a new <ol>-element, append my scraped items, run Hyphenate:hyphenate (ofcourse searching for the classname as shown in your example) and then append the children of the <ol>-element to the existing one.
I'm going to check how that solution compares to my current one.

Kind regards,
Yannick
