### ISSUE TITLE
How to run Hyphenator several times ?

### ISSUE THREAD

**Issue by ytrezq** [mnater/Hyphenator#234]
Currently one would call`Hyphenator.run()`. However, pages can dynamically be updated. Requiring to run Hyphenator again without inserting a soft hyphen twice *(inserting a soft hyphen hyphen were it was already done)*.

**Comment by mnater** [comment]
Hyphenate the dynamically loaded elements with Hyphenator.hyphenate() (https://github.com/mnater/Hyphenator/blob/wiki/en_PublicAPI.md#mixed-hyphenatorhyphenatemixed-target-string-lang).

See this discussion: https://github.com/mnater/Hyphenator/issues/233

**Comment by ytrezq** [comment]
No because in my case the content is text which can be controlled by the user. But I let’s explain :

The user submit text input from a textarea element.
\&shy is inserted with Hyphenator.hyphenate().
The user click on the edit button only for adding some words *(word removing is not allowed)*.
Hyphenator.hyphenate() is runned a second time on the user input. inserting things like \&shy twice at some places.

Ok it should be easy to avoid this by removing all \&shy but I think this library have some methods for that case.

**Comment by mnater** [comment]
That's interesting.
The function hyphenateWord that is called by Hyphenator.hyphenate() internally checks if the word is already hyphenated (i.e. if the word contains the hyphen character) and, if so, just returns the already hyphenated word. Therefor the soft hyphen shouldn't be inserted twice.
Or there's a bug.
Or another script replaces the soft hyphen (&#173) inserted by Hyphenator with something else and hyphenateWord doesn't see that this word has already be hyphenated…

Would it be possible provide an example (code or link) where I can see what happens?

**Comment by ytrezq** [comment]
Sorry.

**Comment by mnater** [comment]
?
