### ISSUE TITLE
Hyphenator fails when using PageSpeed

### ISSUE THREAD

**Issue by fidoboy** [mnater/Hyphenator#238]
Not sure why but hyphenator is also adding hyphenation to my javascript code, for that reason, when using Hyphenator together with PageSpeed it causes errors. It seems like a bug. Isn't Hyphenator avoiding the ```<script>``` tags? There is any way to fix this?

**Comment by fidoboy** [comment]
NOTE: I'm using Hyphenator_Loader.js

**Comment by mnater** [comment]
Hi

Hyphenator.js itself doesn't hyphenate script tags (see https://github.com/mnater/Hyphenator/blob/master/Hyphenator.js#L211 for a list of all tags that aren't hyphenated).

What seems to happen here is that your script tag gets hyphenated by CSS when you're using a browser that supports CSS-hyphenation for your language.

Does the same thing happen when you use a browser that doesn't support CSS-hyphenation (e.g. Chrome)?

My step-by-step instructions on https://github.com/mnater/Hyphenator/blob/wiki/en_HowToUseHyphenator.md#step-by-step-easy-with-hyphenator_loaderjs are missing a CSS-class to inhibit hyphenation. I'll fix that.

I don't understand the issue with PageSpeed, though. Is that Google PageSpeed? Could you please explain in more details? A link or some code that shows the problem would be great, too.

Kind regards,
Mathias
