### ISSUE TITLE
New Safari Browser, Google Webfonts, and Hyphenator

### ISSUE THREAD

**Issue by Theddie** [mnater/Hyphenator#239]
First of all: thank you very much for this amazing piece of code! I wouldn't know what to do without it!

Unfortunately, the new Safari 9 seems to have problems with the script (both on MacOSX and iOS) -- at least if Google Webfonts are used: cf. the screenshot. If I remove the Google Webfonts, everything is fine again. But then again, the site worked perfectly with the webfonts on all previous Safari versions and continues to do so on all non-Safari browsers.

Could you please have a look at this? In the meantime, I removed the hyphenation from the site in order to ensure that Apple users can access it without much trouble, but I kept it on a guinea pig version of the site that I use for experiments. I gladly tell you the link to that if that helps. 

I am happy to provide any further information -- just let me know. Thank you!

![screenshot](https://cloud.githubusercontent.com/assets/15087211/10448581/0a8bac5e-718e-11e5-9aad-70784e94b7cb.png)

**Comment by mnater** [comment]
Hi

Thanks for submitting this issue. That looks really strange…
This week I'm on vacation. I'll have a closer look at it when I'm back.

A link would be helpfull to reproduce the issue.

Kind regards
Mathias

**Comment by mnater** [comment]
Hi

This was hard to find, but I think I got it now (thanks btw for the link in the private mail, that helped a lot).

It's a bug in Safari/Webkit:

When all of the following is true:
- a font that supports automatic ligatures is used (in your case it's Source Sans Pro) and ligatures are enabled
- there is at least one ligature on the same line (in your case 'ft' in Gesellschaft)
- soft hyphens are used in that same line

…then characters around soft hyphens after the ligature are messed up.

It seems like this is an old issue (https://bugs.webkit.org/show_bug.cgi?id=30024) and something changed in Safari 9 to make this issue more visible. (Maybe they enabled ligatures by default? I haven't checked with older Safari, yet.)

Workarounds:
- disable automatic ligatures with the CSS-property `-webkit-font-variant-ligatures: no-common-ligatures;`
or better
- use CSS-hyphenation (it's currently disabled on the page you linked to – why?)

Regards,
Mathias

**Comment by mnater** [comment]
https://bugs.webkit.org/show_bug.cgi?id=150329

**Comment by Theddie** [comment]
Thank you very much for having a look into the matter and the detailed explanations! A very annoying bug -- great that you already submitted it!

I am also very grateful that you provided workarounds. I had trouble with the first one, but the second one works. I found that using CSS-hyphenation not only makes no difference with regard to the bug in Safari -- it's still there --, but also results in Firefox' not hyphenating at all.

All the best,

Theddie

**Comment by solverat** [comment]
:thumbsup: thanks @mnater for getting into this - saved my day. ;)

extend the style with `-webkit-font-variant-ligatures: no-common-ligatures;` fixed it.

**Comment by samtazbu** [comment]
Thanks to each of you for addressing this unfortunate problem and finding solutions... I am unfamiliar with this level of coding. Could one of you please indicate where the "script" code of useCSS3hyphenation - from the wordpress interface?

**Comment by mnater** [comment]
The wordpress plugin that uses Hyphenator.js (https://wordpress.org/plugins/hyphenator/) is provided by other developers and unfortunately doesn't reflect all possible settings of Hyphenator.js.
Either use Hyphenator.js directly (http://mnater.github.io/Hyphenator/) or ask the developers of the wordpress plugin to improve their interface…

**Comment by samtazbu** [comment]
Sad news :( but thanks for the quick response! :)

**Comment by mnater** [comment]
The vendor-prefix in `-webkit-font-variant-ligatures: no-common-ligatures;` is no longer supported in Safari 9.1.
Use both, the prefixed (for Safari < 9.1) and the unprefixed (for Safari >= 9.1):


```
-webkit-font-variant-ligatures: no-common-ligatures;
font-variant-ligatures: no-common-ligatures;
```

**Comment by samtazbu** [comment]
Thanks Mnater, works well !

**Comment by Maxikq** [comment]
@mnater Thank you! You're the savior!

**Comment by tormaid** [comment]
Thanks, @mnater! Worked perfectly for me, too.
