### ISSUE TITLE
Provide option to control the minimal amount of chars left and right of a hyphen

### ISSUE THREAD

**Issue by mnater** [mnater/Hyphenator#240]
Some thoughts:

- In some cases (e.g. in a title) splitting the last word towards the end doesn't look very nice.
- leftmin and rightmin are currently set by the pattern file. (These values could be used as default and an option could overwrite them. This would be nice to be specific for certain classes -> need to implement multiple classes.)
- then an implementation of hyphenate-char-limits (http://www.w3.org/TR/css-text-4/#hyphenate-char-limits) is obvious.

- another solution is to use this restriction only on the last word of a text element.
- There's already the option `orphancontrol` which doesn't hyphenate the last (two) word(s).
- It would be easy to use some values (like in hyphenate-char-limits) to control the hyphenation of such a last word…

**Comment by odie2** [comment]
Hi,

Also requested here - https://wordpress.org/support/topic/great-but-not-there-yet

Greetings
