### ISSUE TITLE
Please add to cdnjs (including language patterns) :-)

### ISSUE THREAD

**Issue by jakob-e** [mnater/Hyphenator#241]
https://cdnjs.com/

**Comment by mnater** [comment]
can.js looks like a great project.
I could add Hyphenator.js and the patterns.
But having the patterns in separate files is slow. It's much faster to merge the script and the necessary patterns in one file: this uses only one http-request and the script hasn't to to idle while waiting for the patterns to be loaded (use mergeAndPack.html as described on https://github.com/mnater/Hyphenator/blob/wiki/en_HowToUseHyphenator.md#using-hyphenator-on-your-website).
Further there may be issues with same-origin-policies in various browsers…

Adding a merged version for each language isn't an option either (this would result in 43 scripts given the 43 languages Hyphenator actually supports, not to speak of all possible multi language combinations…)

Feel free to fork and add your custom script – I won't.

Regards,
Mathias
