### ISSUE TITLE
Synchronous XMLHttpRequest warning message in Chrome and Opera

### ISSUE THREAD

**Issue by tmb-github** [mnater/Hyphenator#245]
The hyphenator is apparently causing this warning message to appear in the developer's console in Chrome and Opera only:

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience; for more help, check http://xhr.spec.whatwg.org/`

It points at this code in jquery.js:

`xhr.open( options.type, options.url, options.async, options.username, options.password );`

...but the source seems to be somewhere in the hyphenator code that calls this JQuery routine. This happens regardless of whether I serve the Hyphenator from the local site itself or from my separate, cookie-free static domain. Also, it is only reported by Chrome and Opera. 

What is causing this and what can be done to fix it?

**Comment by mnater** [comment]
Hi

Hyphenator.js doesn't depend on JQuery.
The only XMLHttpRequest it makes is to check if the patterns can be loaded (https://github.com/mnater/Hyphenator/blob/master/Hyphenator.js#L1942) – the async flag is set…

So I honestly don't know what causes this warning.
Could you send a link to a page where this warning occurs, please?

Thanks,
Mathias

**Comment by tmb-github** [comment]
Dear Mathias,

Oddly, I've discovered the error/warning message is generated only when I
run my site on localhost servers on my computer. The message is displayed
in the developers console both in the current version of XAMPP and Bitnami
WAMP on Opera and Chrome. However, with identical files uploaded to my live
site, no such error/warning message is generated in the developer's console
in Opera and Chrome.

I'm certain it's the hyphenator, because when I rem-out the code that calls
the hyphenator code on my local servers, the error message does not appear;
it's only when the hyphenator is being loaded locally that the warning is
issued. Since this won't reproduce on my live site, I can't send you a link
where you can see it in action. If you would like to see it on my localhost
via Skype, etc., I would be happy to set a time with you to do so. But
otherwise, you may as well footnote this as a strange quirk that only seems
to manifest during localhost testing, as it's not present during live-site
execution of the code.

(Obviously, I have no idea why this would be; if you have any ideas and
wish to send me some things to try, I'd be very happy to do so, because
I've had to resort to adding this conditional code to prevent the error on
localhost:

$.ajaxPrefilter(function( options, originalOptions, jqXHR ) {
options.async = true;
});

...but this is not ideal, as it may block serious error messages as I
develop my site on localhost that *will* subsequently appear on the live
server site.)

Many thanks,
Tom
ᐧ

**Comment by mnater** [comment]
Dear Tom

When scripts behave differently when they are loaded from localhost or from a server it's often one of the following problems:
- Loading from localhost is much faster. So the scripts are loaded almost simultaneously. If one script infers with another this could cause some issues. On the contrary, if loaded from a server there may be some milliseconds where one script is loaded and executed while the other script is still loading. This highly depends on how the scripts are called from your site.
- protocols differ: I once had an issue where someone loaded scripts locally with the file:// protocol while using http:// on the server… (this was set automatically by his IDE)

Further: jQuery loads scripts that are appended with .html() async.

This leads to the following question:
How do you call Hyphenator on your site?

(A link to the live site would help, too – where I can inspect your code. Or you paste some code here…)

Kind regards,
Mathias

**Comment by tmb-github** [comment]
Dear Mathias,

We're in luck, as I discovered a quirk with the performance of the site. I
can share with you two different versions of the site at two different
URLs, one that displays the error message in the developer's console, and
another that does not display the error.

First, however, bear with me as I explain how the sites function, as this
is crucial.

I have two mode for the sites:

* A "static" mode, in which all "static" content (js, images, css, etc.)
are delivered from a separate, cookie-free, "static" domain.
* A "dynamic" mode, in which all all "static" content (js, images, css,
etc.) are delivered from the same URL as the main site.

The default mode is the "static" mode, because it eliminates the useless
cookie delivery for the static content and thus saves bandwidth and
execution time. The other mode is an administrative mode, in which I sign
on to the site to upload images, make changes, add text, etc. In that mode,
the site switches to what I call "dynamic" mode or "dynamic delivery" mode,
in which all of the static content comes from the main site itself instead
of from the separate static URL.

Last night after I sent you the message that everything seemed to be
working fine on the live version of the site, I logged onto the site in
administrative mode--which is "dynamic" mode--and the error messages
reappeared. I signed out of administrative mode, and the error messages
disappeared. I then went back into admin mode, and messages again
reappeared. Aha!

So, something odd is happening when the site is retrieving the hyphenator
from the live site itself, instead of from the separate static-content,
cookie-free URL.

Fortunately, I another "unlisted" URL where I do testing of new code before
I put it on the live site, and I also have a switch in my code that can
make the site switch to "dynamic" delivery without having to log-in to the
site as administrator, so I've done the following:

I've left the main live site untouched, and I've set the parallel "testing"
site to "dynamic" mode. That way you can visit each site and see the error
message appear in one but not in the other.

First, though, let me explain how the site functions, as it's quirky, and
it's not obvious how to see the relevant source code on the affected pages.
It is my art site, which was first built by a web developer who was
extremely unreliable and a bit nuts. I am a programmer, myself, but my
experience up to this year has been exclusively in desktop applications,
not web applications. I've had to learn web programming to be able to
maintain and improve the site, and I've spent most of my free time this
year improving the site, which was in shabby shape because of the original
developer.

Where you'll see the errors will be in the "Galleries", which you may
access from the "Galleries" drop-down list in the menu at the top of the
screen. The original developer took a clever tactic to handle the gallery
problem--which was that several different galleries might have the same
images and text--by using two main scripts:

1) gallery.php, which is the generic script for calling a gallery, and

2) artwork.php, which is the generic script for calling a specific artwork.

When a gallery is opened, gallery.php is called. Clicking on images in the
gallery--accessible by an image carousel at the top--will cause the
corresponding work to be generated with artwork.php (which creates a
separate HTML page viewed within the larger gallery HTML page) and then put
into a hashable cache. In that way, viewing the source code of gallery.php
does *not* reveal the code that generates the art image + text; you have to
select the accompanying text beside an art image by right-clicking on the
text and going to "inspect element" to see that embedded HTML page and
where it is, hidden in the DOM.

I sped up the workings of the galleries by making a gallery, when first
opened, cycle through *all* of its works and store them in session storage.
That way, clicking on images in the carousel doesn't trigger a database
query and content retrieval to populate the artwork.php script which is
then cached; instead, it's all been cached when the gallery loads. (This
wasn't the case the way the original developer designed it; any previously
unviewed image that you clicked on in the carousel would trigger a database
query, etc., thus slowing down performance within the gallery.) Also,
because I'm putting everything into session storage, if I open a different
gallery that has some identical items found in a previously-opened gallery,
then it doesn't have to retrieve all the data for that item, as it's
already in session storage.

But I don't do this in admin mode, which is dynamic mode, because if I make
changes to something and I want to see the changes, I don't want the site
to pull up the already cached content; therefore, in "dynamic" mode,
nothing is stored in session storage, and everything is retrieved from
scratch (i.e. each gallery retrieves all items from scratch) each time it
is called.

This means that on the main live site, you will see data XHR retrieval info
in the console for items the first time you open a gallery that contains
those particular items, but you won't see anything in the console the
second or any subsequent times you return to that gallery, as its contents
have already been loaded into session storage (and this goes for identical
images in different galleries; once they have been loaded into session
storage in one gallery, they're loaded for any other gallery you should
open that happens to contain them).

But this is not true for the parallel, "dynamic" site: since it's in
"dynamic" mode, nothing is going into session storage, and thus you'll see
in the console the same XHR messages and the error message--which is what
we're trying to debug.

Also, you'll notice that for every image loaded, the hyphenator has to be
loaded, because it has to be present in the (hash-cached) artwork.php,
which I guess you would call an embedded HTML page that then appears one
for each image in each gallery. Putting the hyphenator in the "parent"
gallery.php that calls and caches the pages of artwork.php did not work for
the hyphenator...I had to call it on the artwork.php script, so it gets
called and included (sigh) for each image in each gallery. (And this is
part of the design of the gallery that I have inherited from the original
programmer; I spent several weeks preparing all of the database
queries--some 53 distinct queries are found throughout the site, and he had
not prepared any of them; he also hadn't indexed the tables in the
database, etc. So my clean-up work has been mammoth and the universe seems
to be telling me I should switch to web programming, and, in fact, I'm
using this site as a touch-stone for learning web programming, as the
developer wrote everything by hand--no framework--and it uses every one of
the standard languages and tools for web programming, including AJAX calls,
etc.)

With thanks for wading through all of that, which I think you'll appreciate
once you see the sites, here they are:

Main "static" site: thomasbrodhead.com
Testing "dynamic" site: thomasbrodhead.dreamhosters.com

(The static content site from which the JS files, etc., are delivered is
tmb-static.com, but there's no reason to go there, as its index.php is just
a text message.)

The two sites will function as indicated. To see the error in action, open
the *testing* site with Chrome developers tools also open and click on the
galleries menu item, and select, say, "2015". That is a smaller gallery and
will load quicker than "New and Notable", which is larger and takes longer
to load.

---> For reasons unknown, my site performs slowly in certain parts of
Europe. In the U.S., it opens and executes rapidly. My host is DreamHost,
and I have no idea why there should be a performance delay in certain parts
of Europe.

In a different tab (private browsing for both, I would guess), open the
Main site and open the same gallery. You should see no error message in the
console.

---> The "Synchronous XMLHttpRequest" error message appears exactly once
per gallery, regardless of the number of items in the gallery, and will
always be the second item down the list in the console.

If any of this does not make sense, or you need more information about the
site and how it is doing its work, please let me know.

Many thanks in advance for your help,
Tom

**Comment by mnater** [comment]
Dear Tom

Thanks for the links and the explanations.

If I correctly understood, your site basically does the following (gallery.php):
1. it loads the contents for each artwork (an html text-string) either from sessionsStorage or from server
2. it appends this text-string to the .bbq-content-div
The loading and appending is done by jQuery.

Now the text-string contains a script tag (Hyphenator_Loader.js). jQuery will automatically load this script for you when you include the string in your existing site. This load is done synchronously, because jQuery (correctly) assumes that the script needs to be loaded and executed before adding further content.

That's why there is this warning message and that's why the message disappears when you remove this script tag from the loaded content.

There's nothing I can change in Hyphenator(_Loader).js to fix this, because the issue is completely in your hands, sorry.

Kind regards,
Mathias

PS: IMHO your approach to loading the gallery is very complicated and I can't see any benefit of it.
Why don't you just serve the entire gallery in one huge html, hiding all artworks but the one the user clicked at in the top bar?

**Comment by tmb-github** [comment]
Dear Mathias,

Thanks for the detailed response. What may pose a problem for your analysis
of it is that the hyphenation is performed correctly and completely by the
Hyphenator (including hyphenations I've added for some foreign words not
commonly found in English) on both sites, which contradicts the need for
the loader to be loaded asynchronously, as one is doing it synchronously
(the main site) and the other asynchronously (the test site as I've set it
up for you to examine). This also doesn't explain why there are _no_ error
messages on the main site when it is run from the live server but error
messages _do_ appear when I run it on a localhost (XAMPP or Bitnami WAMP)
on my own computer. Could you please explain why this would be the case? I
don't understand.

Many thanks,
Tom
P.S. The complication of the site's construction I inherited from the
original programmer. There is method to his madness, as each item in each
gallery requires database queries to retrieve all of the text for each
artwork as well as the name of the work to retrieve from the server [the
images are, of course, stored on the server, not as blobs in the database]).

**Comment by mnater** [comment]
Please understand that I can't debug your code.
