### ISSUE TITLE
AngularJS integration ?

### ISSUE THREAD

**Issue by Randall94** [mnater/Hyphenator#248]
Is there a way to integrate Hyphenator with AngularJS ?

I was quite surprised that I haven't found a solution for this...
Thank you.

**Comment by mnater** [comment]
Unfortunately I'm not very familiar with AngularJS – but I believe there's always a way…

As far as I understood it's an MVC?
There could be some interesting challenges when the model changes and the view is updated:
- How does Hyphenator.js now about new contents?
- Where will text be hyphenated: in model or in view?

Personally I don't have time to work on this. But keep me updated if you work on it and don't hesitate to ask questions and request features that would be necessary in Hyphenator.js

Kind regards,
Mathias

**Comment by Randall94** [comment]
Okey, thank you. I will keep in touch in case I come up with something useful.

**Comment by mnater** [comment]
Thanks
