### ISSUE TITLE
Creating colored syllables

### ISSUE THREAD

**Issue by Shen** [mnater/Hyphenator#252]
Hi,
is it possible to create systematic bicolored syllables with your script?
For example to create some text like this one:
www.lehrmittelperlen.net/images/image/ab_0101_2015/Leseverstehen_2_Silben.PNG
If not, would it be difficult to program this, based on your script?

**Comment by mnater** [comment]
Hallo

Danke für die Anfrage.

>>is it possible to create systematic bicolored syllables with your script?
Nein, leider geht das mit Hyphenator nicht – und zwar aus zwei Gründen:

i) Worttrennung am Zeilenende hat nicht immer etwas mit Silben zu tun. Das Wort »beinhalten« z.B. hat die  Silben »be-in-hal-ten« sollte aber nicht »bein-halten« getrennt werden, da dies den Lesefluss stört.
Hyphenator.js bzw. die Trennmuster finden also nicht immer alle Silbenfugen, sondern nur solche, die auch als Trennstelle in Frage kommen.

Bei den meisten Wörtern spielt dies aber keine Rolle. Aber da steht noch folgendes Problem im Weg:

ii) Um die Silben einzufärben müssten sie jeweils in ein <span> gepackt werden. Hyphenator arbeitet aus  Performance-Gründen nicht auf DOM-Level sondern direkt auf dem Text; kann also in der aktuellen Code-Basis keine DOM-Manipulationen an den einzelnen Wörtern vornehmen.

Man müsste also i) die neue Muster berechnen (aus einer nach Silben getrennten Wortliste: http://projekte.dante.de/Trennmuster) und ii) ein paar Zeilen in Hyphenator anpassen. Beides zusammen hat dann aber nix mehr mit Hyphenator zu tun und hat somit keinen Platz in diesem Projekt – das wär dann der Syllabificator oder so ;-)

**Comment by Shen** [comment]
Hallo,
danke für die ausführliche Rückmeldung mit den vielen Hinweisen. Das Dante-Projekt kannte ich noch gar nicht. Leider geht das über meine Programmierfähigkeiten hinaus, aber es ist gut zu wissen, dass meine Idee theoretisch auf der Basis von Hyphenator möglich wäre.
