### ISSUE TITLE
Turn off hyphenator only on particular DOM element.

### ISSUE THREAD

**Issue by matedon** [mnater/Hyphenator#259]
Hi!

Just an example:
```
<div id="demo"><span id="skipAfter"></span></div>

Hyphanator.run(document.getElementById("demo"), "hu");
Hyphanator.clear(document.getElementById("skipAfter"));
```

How is it possible not just toggle the whole plugin but only turn off particular elements?

Thank you.

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenator/blob/wiki/en_PublicAPI.md#properties-classname-and-donthyphenateclassname

**Comment by matedon** [comment]
Sorry,

I prisiate your attentiont but your given help link doesn't solve the basic problem.
How can I switch on and then switch off the Hyphenator on the fly?
How can I add hyphen sign with world brake and restore them when it's needed?

Please give me complete answer if you are able to!

Thank you!

**Comment by mnater** [comment]
Hi
I'm not shure if I understand what you are trying to do. Maybe this is what you are looking for:

https://github.com/mnater/Hyphenator/blob/wiki/en_PublicAPI.md#void-hyphenatortogglehyphenation

If not, please explain in more details…

**Comment by matedon** [comment]
Here is my specific application with hyphenator:

http://ckeditorhyphen.herokuapp.com

I want to use the Hyphanator as a CKEditor plug-in.
It is working but I can not switch off Hyphenator in paragraphes.

My github repo laying here:
https://github.com/matedon/ckeditorHyphen
