### ISSUE TITLE
Dehyphenation

### ISSUE THREAD

**Issue by TuningGuide** [mnater/Hyphenator#260]
Is it possible to dehyphenate text with Hyphenator?

**Comment by TuningGuide** [comment]
My scenario is: I have a hyphenated text from a text file and would like to concat all words which are split on line ending due to hyphenation. So it would be cool I there is a function / npm package which provides hypenisation / dehyphenisation on text (for nodejs).

**Comment by mnater** [comment]
That's one line of code.
You won't need a package!

**Comment by TuningGuide** [comment]
I do not want to unconditionally lose / replace all "-" signs in my text. My approach would be to search all -\n concat the part before and after -\n hyphen them and check if it would split at the point where it splitted in the text.

**Comment by mnater** [comment]
This won't work.
e.g.:
````
water-
bottle
water-bottle -> waterbottle -> wa-ter-bot-tle
````
How would a program know what kind of hyphen it was?
Was it waterbottle that was hyphenated to fit the lines or was it water-bottle and it was just convenient to split after the "-"?

I don't see a solution…
