### ISSUE TITLE
Minify for Hyphenator.js and Hyphenator_Loader.js

### ISSUE THREAD

**Issue by pvnr0082t** [mnater/Hyphenator#263]
Hi @mnater ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. We want to host this library.
I think files in `patterns` folder don't need to be minified but `Hyphenator.js` and `Hyphenator_Loader.js` should be minified.
Because the auto-updater in cdnjs doesn't support partial minification, I would like to ask if it's possible to provide minified file for `Hyphenator.js` and `Hyphenator_Loader.js`. Thank you.

https://github.com/cdnjs/cdnjs/issues/8050

**Comment by PeterDaveHello** [comment]
`patterns` can also be minified, it's not minified yet. Maybe a dist folder with pre-minified files will be a good solution.
