### ISSUE TITLE
modalLangDialog.html need to be added in cdnjs?

### ISSUE THREAD

**Issue by pvnr0082t** [mnater/Hyphenator#266]
Hi @mnater ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
We don't support `html` on CDN and we found that `modalLangDialog.html` in https://github.com/mnater/Hyphenator/blob/master/Hyphenator.js#L1494. I'm not sure if it can work without adding this file. Could you please tell me if it should be added in cdnjs? Thank you.

https://github.com/cdnjs/cdnjs/issues/8050
https://github.com/cdnjs/cdnjs/pull/8282

**Comment by mnater** [comment]
Hyphenator.js can work without modalLangDialog.html
It's just a fallback if Hyphenator.js can't find a `lang`-attribute…
