### ISSUE TITLE
can't toggle off non-ASCII hyphenchar

### ISSUE THREAD

**Issue by bdenckla** [mnater/Hyphenator#267]
I can't toggle off a non-ASCII hyphenchar such as middle dot (·) (U+00B7) ('\u00b7'). Am I doing something wrong? Is this a bug or a feature?

**Comment by mnater** [comment]
This should work.
I don't know if you are doing something wrong, since I don't know what you do…

Please post some code or a link.

**Comment by bdenckla** [comment]
1. Hair space as hyphenchar (won't toggle off): http://bdenckla.github.io/efs/rr/great-expectations-hyphenator-js.xhtml
1. Middle dot as hyphenchar (won't toggle off): http://bdenckla.github.io/efs/rr/great-expectations-hyphenator-js-mid-dot.xhtml
1. Pipe as hyphenchar (toggles off just fine): http://bdenckla.github.io/efs/rr/great-expectations-hyphenator-js-pipe.xhtml

**Comment by mnater** [comment]
Sorry for the late response.
Should work with the latest fix.
Thank you!
