### ISSUE TITLE
Merge And Pack tool - Allow user to manually call Hyphenate_Loader.init

### ISSUE THREAD

**Issue by kiprobinson** [mnater/Hyphenator#269]
In the merge and pack tool, when using the hyphenate loader, the code to initialize the loader is appended to the end of Hyphenate_Loader.js.

In my case, I want to call that dynamically, i.e. only passing the test languages for the current user's language. If a user is using French, there's no need for me to test if their browser supports German, for example.

You could tweak the tool so that it doesn't include this part, but provides the user with the script that they need to put in a separate script tag on the page.

**Comment by mnater** [comment]
I'm not sure if I understood what you mean:

Hyphenator_Loader.js has to test if a browser supports the language of the websites content.
E.g. a browser needs to support german hyphenation if the website is german (even if its browser is set to french). So the current user's language is irrelevant…

**Comment by kiprobinson** [comment]
I mean, the last part of Hyphenate_Loader.js generated by merge and pack tool is this:

    Hyphenator_Loader.init({"en":"hyphenationalgorithm","de":"Benachrichtigen","fr":"Amortissements"},"./Hyphenator.js",{useCSS3hyphenation:true});

I went and took that out of the generated file, and put it in my server-side code. Simplifying my code, it looks something like this:

    <script src="Hyphenate_Loader.js"></script>
    <script>
      Hyphenator_Loader.init(
        {
          "en":"hyphenationalgorithm"
          <?php if($userLanguage == "de") { ?>,"de":"Benachrichtigen" <?php } ?>
          <?php if($userLanguage == "fr") { ?>,"fr":"Amortissements" <?php } ?>
         }
    </script>


If the user is using French, and their browser supports French, but doesn't support German, there's no reason we should load the German data. When I say "user's language", I mean the logged-in user's language preference in my own system - i.e. which version of the UI the user is seeing.

**Comment by mnater** [comment]
Now I understand, thanks for clarification.

Although I won't change the merge&pack-tool to support this special case – it's cluttered enough already and you've found a good work-around.

Regards,
Mathias
