### ISSUE TITLE
Provide example test languages

### ISSUE THREAD

**Issue by kiprobinson** [mnater/Hyphenator#270]
To use Hyphenator_Loader.js, I need to provide a test string that is at least 12 characters long in each language I want to support. It would be helpful if you provided an example test string for each language.

Even better, if that test string was already coded, so that we could just pass something like `['en', 'de']`, instead of `{"en":"automatically","de":"Silbentrennungsalgorithmus"}`

**Comment by mnater** [comment]
My intent is to keep Hyphenator_Loader.js as small as possible.
Providing coded test strings would enlarge the script by about 400 bytes (i.e. about 17%).

**Comment by kiprobinson** [comment]
Makes sense, but could you provide them in your documentation maybe? I don't know of a way to quickly look for large words in particular languages.
