### ISSUE TITLE
Hyphenator_Loader still requires patterns subdirectory

### ISSUE THREAD

**Issue by kiprobinson** [mnater/Hyphenator#271]
The instructions on the merge and pack tool make it sound like only the Hypheantor.js and Hyphenator_Loader.js files are required. But it seems that the "patterns" subdirectory is also required. If I don't have it present, I get 404 errors in my dev console when trying to load (for example) de.js.

It doesn't seem to matter whether I check or uncheck the option for "Enable remote loading of language patterns." The generated Hyphenator.js code is the same in both cases.

There seems to be caching going on--after I put the patterns directory there, everything worked fine. I removed the patterns directory, and everything still worked fine, even on an "Empty cache and hard reload" in Chrome. The only way I was able to repro the original issue was to load it in an Incognito tab.

**Comment by mnater** [comment]
Yes, the "patterns" directory is also required.
I'll have to improve/correct the instructions. Thanks for the hint.

Caching of patterns happens in DOM-Storage (if not deactivated) – you'll have to clean the DOM-Storage.

**Comment by mnater** [comment]
updated instructions in 8a7d720
