### ISSUE TITLE
classname not applying on the child elements

### ISSUE THREAD

**Issue by PoojaRaval** [mnater/Hyphenator#272]
Hi,

i have 2 issues for applying classname.

1. i have created tabular structure which i have created with div's columns. in that various text is coming. so instead of applying hyphenate class on each element text, i applied classname to my main listing div. but it is not applying in the child text elements. if i apply the class on specific element, it is working. So please tell me if applying classname on parent will apply to its child or not.

2. how to give multiple classes to the classname? also inheritance of element will work and how should be it given?

Hope you have answers and solution to my queries.

**Comment by mnater** [comment]
Hi

@1: Yes, child elements should inherit from parents.
Could you please send me a link to your site or paste the html. So I can check why it isn't working.

@2: Multiple classes are not supported in Hyphenator.js – this feature is implemented in upcoming (and still early beta) Hyphenopoly.js (https://github.com/mnater/Hyphenopoly)

Thank you and kind regards,
Mathias

**Comment by PoojaRaval** [comment]
hi Mathias,

thanks a lot for the quick response. i created another html for your reference and then found out the issue. the child element is inheriting from the parent class, but the issue is different. if i am using <label> tag the hyphen is not working, and so if i replace it with the other tag, like <div> or <p> it is working fine. i have created my site using many label tag's so won't be able to modify in the site. 
Can you please help me out for this issue?

**Comment by PoojaRaval** [comment]
well i found out the solution :) in hyphenator.js, by default there was _**var dontHyphenate**_ in which `label `tag was written. i removed it, and now its working fine.

Thanks a lot.

**Comment by PoojaRaval** [comment]
sorry, but again i found another issue. we are getting email id's also in the column. but if the email id is large, it will truncate rest on next line. but in this case, the hyphen's are not working.
please let me know the solution for email id's, as it is having special characters.

**Comment by mnater** [comment]
Hi

Maybe er should allow label to be hyphenated.

In e-mail adresses and urls Hyphenator.js uses zero width spaces unstead of hyphens. (You don't want hyphens there, since this would alter the address)
