### ISSUE TITLE
Same Hyphenator class is adding multiple times on same element

### ISSUE THREAD

**Issue by anubhavjain04** [mnater/Hyphenator#274]
**Browser**: Firefox
**Lang:** de
I have a requirement to hyphenize element's text when adding runtime. When I run hyphenator second time on same page, my old element added same class again.

Below **(el.className = el.className + ' ' + css3hyphenateClass;)** line doing this.

Please fix it.

Ex:
`<span class=" Hyphenator592css3hyphenate Hyphenator592css3hyphenate" style="">Zeiterfassung</span>`

```
useCSS3 = function () {
                            css3hyphenateClassHandle =  new CSSEdit(contextWindow);
                            css3hyphenateClassHandle.setRule('.' + css3hyphenateClass, css3_h9n.property + ': auto;');
                            css3hyphenateClassHandle.setRule('.' + dontHyphenateClass, css3_h9n.property + ': manual;');
                            if ((eLang !== pLang) && css3_h9n.property.indexOf('webkit') !== -1) {
                                css3hyphenateClassHandle.setRule('.' + css3hyphenateClass, '-webkit-locale : ' + eLang + ';');
                            }
                            el.className = el.className + ' ' + css3hyphenateClass;
                        },

```

**Comment by mnater** [comment]
Hi

Thanks for reporting.
I haven't tested this, yet. But judging from your description you are calling `Hyphenator.run()` repeatedly. This is not necessary. Try to use `Hyphenator.hyphenate` (https://github.com/mnater/Hyphenator/blob/wiki/en_PublicAPI.md#mixed-hyphenatorhyphenatemixed-target-string-lang) instead.

**Comment by anubhavjain04** [comment]
Okey. Thanks for your suggestions. I will try this.
