### ISSUE TITLE
Add basePath config option and/or expand detection to include "Hyphenator.min.js"

### ISSUE THREAD

**Issue by jefferyto** [mnater/Hyphenator#275]
I'm currently loading Hyphenator from cdnjs (using Hyphenator_Loader.js and passing a full url for Hyphenator.min.js). When loading pattern files, it loads them from `//mnater.github.io/Hyphenator/` instead of cdnjs, because it can't find a `script` element with "Hyphenator.js" in the URL.

I suggest adding a basePath config option (detecting the base path can be error-prone since the script file can be renamed to anything) and/or expanding the base path search to include "Hyphenator.min.js" (I imagine this would be a very common file name for those who minify).

As a workaround, I am including this in my HTML:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Hyphenator/5.1.0/Hyphenator.jsx" type="text/plain"></script>
```

Although I'm not certain the `type="text/plain"` will stop all browsers from trying to download the file, it would only lead to a 403 error.

**Comment by mnater** [comment]
Totally agree.
Thanks!

Could use https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript, too (except for IE)

**Comment by rreitmann** [comment]
Detecting the basePath leads to an error in IE 11 when Hyphenator.js was packaged in a vendor.js since in this case path is undefined. I suggest returning the default basePath...
