### ISSUE TITLE
Doubts about Hyphenator

### ISSUE THREAD

**Issue by gusbemacbe** [mnater/Hyphenator#277]
Hello,
1. Does `mergeAndPack.html` really merge the `Hyphenator.js` and many patterns JavaScript files into one file.js? So I did it and it didn't work in my demo test page.
2. Can I merge one merged/minified `file.js` into `<script></script>` on a HTML page?
3. If I add 
   
   ```
   Hyphenator_Loader.init(
               {
                   "en": "Bootstrap",
                   "pt": "Constitucionalização",
               },
               "./Hyphenator.js"
           );
   ```
   
   Will the English word Bootstrap be hyphenated in a text in Portuguese and will the Portuguese word Constitucionalização be hyphenated in a text in English?
4. Do I need to merge `Hyphenator.js` and `Hyphenator_Loader.js` into one `file.js` that `Hyphenator_Loader.init` would work?

**Comment by mnater** [comment]
Hi

@1: Yes. If it didn't work please explain what you did and what went wrong.
@2: Yes
@3: If the word Bootstrap occurs in a Portuguese text (an if it isn't surrounded with span tags with lang="en" attributes) it will be hyphenated following Portuguese rules. Vice versa for Constitucionalização.
@4: No. The purpose of Hyphenator_Loader is to load Hyphenator.js and patterns only if necessary (i.e. browser doesn't support native css hyphenation). (See https://github.com/mnater/Hyphenator/blob/wiki/en_HowToUseHyphenator.md#using-hyphenator-on-your-website)

**Comment by gusbemacbe** [comment]
Hi Nater,

I was going to report, but I fixed the #1. Now it worked. Because I gave a name of Hyphenator to a JavaScript file before and it didn't work. I renamed to hyphenate and it worked. 

In the #2, I copied the whole code inside `<style></style>`on a HTML file and it worked wonderfully.

Please, add Georgian hyphenation. Get the package of Georgian hyphenation from TeXLive:

a)  Get `hyph-ka.tex` from http://tex.tsu.ge/files/

Ah, It seemed that this file has also Hyphenator.js inside, it has some configuration of Georgian hyphenation and has a translation in Georgian! Then get the pattern `ka.js`!

Please, update it. I want to add Georgian to my merged file.

**Comment by gusbemacbe** [comment]
You can also can get the missed languages patterns, as Afrikaans, etc. from here: http://tug.org/tex-hyphen/#languages

Observe that they are in TeX, I do not know if you will understand.

**Comment by mnater** [comment]
I don't know Georgian nor Afrikaans. So I can't check if everything works as expected.

So if you'd like to foster those languages please see https://github.com/mnater/Hyphenator/blob/wiki/en_AddNewLanguage.md

**Comment by gusbemacbe** [comment]
Hi @mnater, I contacted Levan, the Author of the Georgian hyphenation, he updated today and it worked on Hyphenator, check: http://tex.tsu.ge/files/patterns/ka.js 

Maybe he will talk with you.

**Comment by gusbemacbe** [comment]
And the demo of Georgian hyphenation, using Hyphenator: http://tex.tsu.ge/files/WorkingExample.html

**Comment by gusbemacbe** [comment]
Don't add now, he is going to fix the codes this weekend.

**Comment by shoshia** [comment]
Hi all...I'm author of patterns for georgian. Demo link above works fine.
What i see is that patterns on my site use different format. maybe I use older version of hy-phe-nator package on my site..i did not check for a new version long time and google code page is not working anymore.

So I need to convert ka.js pattern file to new format for patterns..
Is any js script available which converts older pattern formats to new compact ones?
may i use it?
if not I need to write for myself and will do this on this weekend.

**Comment by shoshia** [comment]
ok..I converted patterns using this page
http://mnater.github.io/Hyphenator/compressor.html

please check http://tex.tsu.ge/files/patterns/
there is a file ka_new_format.js rename it to ka.js
and try it :) ...
I dont have time right now....
will check later

**Comment by gusbemacbe** [comment]
@shoshia and @mnater, you can check my quick and ready demo: https://codepen.io/gusbemacbe/pen/eEdwdj

Levan, you can fork to fix the codes if you want.

**Comment by mnater** [comment]
Hi
Great work! I'll be happy to merge your pull request.
Thanks,
Mathias

**Comment by gusbemacbe** [comment]
I updated the Hyphenator.js, but I was unable of fixing the bug.

**Comment by gusbemacbe** [comment]
I fixed ka.js and replaced `specialChars : "_აიერთხტუფბლდნვკწსგზმქყშჩცძჭჯოღპჟჰ"` for `specialChars : "აიერთხტუფბლდნვკწსგზმქყშჩცძჭჯოღპჟჰ"`, but it doesn't solve the problem. Let Levan solve it.

**Comment by gusbemacbe** [comment]
@mnater and @shoshia 

It worked now, only if without jQuery.js and materialize.js. But we received a warning. :-(

**Comment by gusbemacbe** [comment]
Ah, I fixed the bug and replaced `Hyphenator.languages["ka"]` for `Hyphenator.languages['ka']`, it worked with jQuery and materialize now.

The updated Hyphenator and ka.js are ready. :-)

[Georgian Hyphenation.zip](https://github.com/mnater/Hyphenator/files/1200409/Georgian.Hyphenation.zip)

Now you can merge them

**Comment by shoshia** [comment]
I think '_' is important in "specialChars" section; Hyphenator.languages["ka"] was generated from compressor script...So it seems compressor bug

**Comment by gusbemacbe** [comment]
Hi @shoshia and @mnater 

It is true!

I uploaded the template and tested both on Github and Codepen, it worked with Georgian hyphenation, but no hyphenation of three languages worked on the collection (list) in the end of the articles. You can check the demos:

1. [Github](https://gusbemacbe.github.io/georgian-hyphen-material-article/)
2. [Codepen](https://codepen.io/gusbemacbe/pen/MvJYXM)

@mnater, you can get the uploaded version of Hyphenator and Levan's `ka.js` from my repository: https://github.com/gusbemacbe/georgian-hyphen-material-article

**Comment by shoshia** [comment]
hi

in li taggs <li></li>

you can put

 <div class="hyphenate">შეგროვება  გრაფიკული დიზაინერი, ხატები, ფონტები და დიდაქტიკური და გრამატიკა წიგნების ნივთები</div>

and  this part in div will be hyphenated

or

<span class="hyphenate" lang="ka">წასვლა სავაჭრო ცენტრიკენ ელეგანტური ტანსაცმლი ყიდვისთვის და იაპონური საკვები ჭამისთვის </span> in <li> tags


________________________________

**Comment by gusbemacbe** [comment]
Ah, it worked now.

**Comment by mnater** [comment]
Hi

specialChars shouldn't contain the underline "_" that's true. specialChars are needed to find words in a text and every char that's not in a-z is considered a "specialChar".
TeX patterns use the dot "." to mark the start or the end of the word. Hyphenator.js-patterns use underline to mark the same (I decided to change that because of issues with the dot in regular expressions and to emphasise the difference of the format).
compressor.html probably produced specialChars with a "_" because it was fed with patterns that already head underline as start/end-makerker.

When I look at the original TeX-Patterns (http://tex.tsu.ge/files/hyph-ka.tex) I see `\lefthyphenmin=1 \righthyphenmin=2` but in ka.js both are set to 2. Is this correct?

**Comment by shoshia** [comment]
yes sorry \lefthyphenmin=1 \righthyphenmin=2 is correct

________________________________
