### ISSUE TITLE
Georgian hyphenation doesn't work in Hyphenator. :-/ 

### ISSUE THREAD

**Issue by gusbemacbe** [mnater/Hyphenator#279]
A Georgian guy added Georgian for your Hyphenator. Check: https://github.com/mnater/Hyphenator/issues/277

I copied his added Georgian parts from Hyphenator file and pasted on my hyphenate file. I also added the part of "ka" pattern on the same file. It didn't work in my HTML test. 

Can you explain why it did not work.

**Comment by mnater** [comment]
Please see https://github.com/mnater/Hyphenator/blob/wiki/en_AddNewLanguage.md

Without any code, I'cant explain…
