### ISSUE TITLE
Provide configuration to control the no of words can be hyphenated in consecutive line ends.

### ISSUE THREAD

**Issue by hkurra** [mnater/Hyphenator#284]
> Like Below example wherein the first image has  2 consecutive line ends hyphenation and the second image has only 1 consecutive line ends hyphenation. there must be some configuration to control this value **(suggested values are 1,2,3 and unlimited)** 

![multi line hyphenation](https://cloud.githubusercontent.com/assets/6569316/20346392/cc3f7726-ac21-11e6-86a6-758a8a36419d.PNG)

![multi line hyphenation1](https://cloud.githubusercontent.com/assets/6569316/20346393/cc477296-ac21-11e6-97cf-5718e7f8ed44.PNG)

**Comment by mnater** [comment]
Hyphenator.js just inserts soft hyphens to give the browsers layout engine more opportunities to break the line. The actual line breaking is done by the browsers layout engine.
The advantages of this approach are: Performance (it's fast), responsiveness (line lengths can easily be adapted to window size) and simplicity
The disadvantage is that we can't know, where the browser actually breaks a line – thus, we can't control consecutive word breaks.

An other approach is to layout text "manually" - i.e. by Javascript using a line breaking algorithm like the one Knuth an Plass developped for TeX. [Bram Stein does that in typeset](https://github.com/bramstein/typeset/), where you have much more fine grained control over how a paragraph is layed out. typeset splits paragraphs in sequences of `<span>`-elements with different `word-spacing` and applies hyphenation where necessary. The result is beautiful but it takes some time and responsiveness is completely lost.

It depends on your use case what you choose…
I won't/can't support this in Hyphenator.js
