### ISSUE TITLE
URL's not correctly detected

### ISSUE THREAD

**Issue by acli** [mnater/Hyphenator#287]
The regex is given as wrd | url | mail and tmp1 | url | mail, so word is always matched first. (If a URL is fed to hyphenateElement, the protocol is matched as a word.)

**Comment by mnater** [comment]
True, but  only if `protocol` has `minwordlength` or more characters.

We could make sure that `wrd` is not followed by `://` (wrd should be something like `[\w-]{6,}(?!:\/\/)`).
Need to test that.

Thanks for reporting!

**Comment by acli** [comment]
I’ll need to clean up my code to see if I can either post a test case or give you a pull request. It is possible that I might have accidentally caused this to become possible while debugging what ended up as issue #288.

What I did was changing the order to url | mail | wrd (or tmp1) (with corresponding changes to the callback). That seems to solve the problem but I’m not sure if there’s another way to fix it without changing the order.

**Comment by mnater** [comment]
Changing order to url | mail | wrd is not good for performance: the regexp will test each word (common case) for an url match (and urls are less common).
The lookahead `(?!:\/\/)` doesn't seem to have a big impact on performance.
