### ISSUE TITLE
orphancontrol = 3 prevents URL’s from being broken

### ISSUE THREAD

**Issue by acli** [mnater/Hyphenator#288]
When the last word in a paragraph is a (very long) URL, Hyphenator correctly breaks the URL, then the orphan control code retroactively removes the non-breaking spaces. 

I guess this behaviour is technically correct, but unexpected. So this is probably a documentation issue. An additional orphancontrol value is probably also desirable (to specify that URL's should still be broken but normal words should be prevented from being hyphenated).

**Comment by mnater** [comment]
Yeah, I'll take that as a documentation issue.
The url can be wrappen in `<span class="urlhyphenate">`…

Thanks for that, too.
