### ISSUE TITLE
URL's with long top-level domains will not be detected

### ISSUE THREAD

**Issue by acli** [mnater/Hyphenator#290]
The url regex specifies host names as (?:www\\.|[a-zA-Z]\\.)?[a-zA-Z0-9\\-\\.]+\\.(?:[a-z]{2,4}))) . Because the top-level domain is matched as [a-z]{2,4}, newfangled domains such as .lawyer would never be matched.

Relaxing the match will probably cause problems so this is probably a documentation problem.

**Comment by mnater** [comment]
True.
Needs some testing if there are problems when relaxing to `{2,}`
