### ISSUE TITLE
This script does some unexpected internet access?

### ISSUE THREAD

**Issue by Erick-BR** [mnater/Hyphenator#292]
(sorry my bad english)
Hi, I had version 3.3.0 on my website and did not require internet connection to work. I always work offline and later I upload to server to make tests on browsers... But version 5.1.0 does not work offline. You can try this just turning off connection. Texts simply disapear. I turn on connection and they appear again.
I really don't fell confortable with support scripts accessing external links since I always include all files they need on my project (images, css..).
This is a bug or script was updated to work this way?
I can change some code to avoid this?
Thank you.

**Comment by mnater** [comment]
Hyphenator.js normally works fine locally without an internet connection.
Hyphenator.js has a fallback: if ressources (i.e. pattern files) can't be found locally it tries to load them over internet from //mnater.github.io/Hyphenator/.
So probably Hyphenator.js can't find (or has no access) to the pattern files locally. Check your setup and watch the console.

**Comment by Erick-BR** [comment]
Ok, was my fault. I place script directly, not by setup as I did on first time. So probably internet connection was required to search language pattern. Thank you for you reply and congratulations for the great script.
