### ISSUE TITLE
accessibility - all words are broken up by screenreaders 

### ISSUE THREAD

**Issue by Veyfeyken** [mnater/Hyphenator#295]
Hi,
The script causes a major problem for visually impaired people using a screenreader. All words are read out in parts. Tested with Jaws on Windows and VoiceOver on Mac.

**Comment by mnater** [comment]
I know.

Hyphenator.js just inserts soft hyphens:
> the character U+00AD SOFT HYPHEN (SHY) is an invisible format character that merely indicates a preferred intraword line break position.
[http://unicode.org/reports/tr14/#SoftHyphen](http://unicode.org/reports/tr14/#SoftHyphen)

So screenreaders should just ignore soft hyphens. Please submit the bug to JAWS and Apple.
