### ISSUE TITLE
hyphen &shy; is ignored

### ISSUE THREAD

**Issue by agru** [mnater/Hyphenator#297]
According to the documentation, I hope I understood it correct, a word is not hyphenated if it contains the defined hyphen-character. In my case it is the default - var hyphen=String.fromCharCode(173);

When now having words with "&shy;" in it, for example Personal&shy;entwicklung, I assume the hyphenation is only allowed at one point in the word, this means between "Personal" and "entwicklung". But in my page the hyphenation is after "Perso" and then "nalentwicklung".

I put the &shy; as it is written here - with 5 letters.

So ... it looks as if this is not working as expected.

**Comment by mnater** [comment]
That's a bug. Thanks for reporting.

**Comment by agru** [comment]
Just picked the code again via Pack & Merge-Tool and included it to our site. Unfortunately no change in behaviour. The word is still broken at a position we do not want. Any hints? Or is there still a problem?

**Comment by agru** [comment]
Here is a demonstration of the problem -> https://lehrerfortbildung-bw.de/lak/
In the headline H1, the word "Personal­entwicklung" should be hyphenated like "Personal" - "entwicklung" or it should be placed completely in the next line and not be hyphenated at all. The &shy; is at the correct position.

**Comment by mnater** [comment]
Ah, in this case it's not Hyphenator.js that computes hyphenation points. It just enables css hyphenation. So it's up to the browser to decide where to hyphenate. (If you "inspect" the word Personalentwicklung you will only find one shy in it.) 

See the [spec](https://drafts.csswg.org/css-text-3/#hyphens-property) for details about words already containing soft hyphens.

**Comment by agru** [comment]
Aaaah ... I think I get the idea now. Got it to stop hyphenation of the word "Personalentwicklung" at a place I do not want. But ...

... sorry for bothering you with these questions and stealing your time, but I would be glad if you'd answer me anyway, although this is not your problem anymore :-).

As far as I can see while debugging, the file /js/Hyphenator.js is not loaded. Do I understand this correctly that the reason is because of the use of /js/Hyphenator_Loader.js - which in turn recognizes that my browser can CSS3-hyphenation?

Are there any browsers that do not support CSS3-hyphenation? Or can I disable this feature for testing purposes in my browser(s)?

BTW: Great tool! And I appreciate your help and thank you!

**Comment by mnater** [comment]
> As far as I can see while debugging, the file /js/Hyphenator.js is not loaded. Do I understand this correctly that the reason is because of the use of /js/Hyphenator_Loader.js - which in turn recognizes that my browser can CSS3-hyphenation?

Correct. If you're interested I started an even smaller and faster polyfill for this purpose: [https://github.com/mnater/Hyphenopoly](https://github.com/mnater/Hyphenopoly)

> Are there any browsers that do not support CSS3-hyphenation? Or can I disable this feature for testing purposes in my browser(s)?

[http://caniuse.com/#search=hyphens](http://caniuse.com/#search=hyphens)

You can try to trick the feature testing with a word that is to short and won't break. So instead of `"de": "Silbentrennungsalgorithmus"` write `"de": "Silbe"` at the end of Hyphenator_Loader.js
I haven't tested this, but should work (make sure to clear DOM_Storage!)

Happy, to answer your questions.
PS: Ich bin Schweizer, wir können das also auch auf Deutsch machen.

**Comment by agru** [comment]
Thank you for your help! Hyphenopoly is marked as beta and I thought I'd not use it on a production site. Perhaps I am going to change, also because it looks as if most browsers are doing the job on their own anyway.

PS: Hatte den Schweizer schon vermutet :-). Auf Englisch hilft es aber vielleicht noch andern DAU's. Viele Grüße über den See - ich sitze in Tettnang auf der anderen Bodensee-Seite
