### ISSUE TITLE
How to fix wrong hyphenation (in German)?

### ISSUE THREAD

**Issue by mpdude** [mnater/Hyphenator#301]
I am trying to use Hyphenator on a German website with many bureaucratic words and have some (IMO) wrong hyphenation points.

One example is Bü‧ro‧kra‧tie‧kos‧te‧nermitt‧lung, which I think should be ...kos‧ten‧er‧mitt‧lung.

Now my question is how this could be best fixed. Should I make a word/pattern correction request somewhere upstream? Will Hyphenator eventually pull the pattern library from somewhere else?

Or, is documentation available how I could grab a "base" word list, amend it with my special words and then rebuild the pattern files myself?

Thanks for any guidance!

**Comment by mnater** [comment]
Kos‧te‧nermitt‧lung is definitely wrong. I'll have to update the german patterns.

(»Bürokratiekostenermittlung« – was für ein schön schreckliches Wort :-)

Hyphenation patterns for german are very well maintained and open source:  [http://projekte.dante.de/Trennmuster](http://projekte.dante.de/Trennmuster)

The patterns Hyphenator.js currently uses are not up to date. Seems like the word `Kostenentwicklung` wasn't on the list, when I updated the patterns the last time…
I'll recompute and update the german patterns based on the current word list these days.

If you're interested in computing your own patterns you will find instructions on the Trennmuster-Site (or you could try https://github.com/mnater/orthos – my port of patgen to javascript).

For workarounds until the patterns are fixed, see https://github.com/mnater/Hyphenator/blob/wiki/en_DealingWithInaccurateHyphenation.md#fixing-bad-hyphenation

Thanks,
Mathias

**Comment by mpdude** [comment]
Awesome, thanks a lot for the helpful reply!

**Comment by mpdude** [comment]
Oh, and did you check that "Kostenermittlung" was added to the list in the meantime, or should I request that?

**Comment by mnater** [comment]
"Kostenermittlung" has already been added.

BTW: Are there other errors you know about?

**Comment by mpdude** [comment]
I'll take a closer look and report back, though it will take some days.

**Comment by mnater** [comment]
german patterns updated: 683b5f8f358b4bfabac6479ba4fbfe10186ef681

**Comment by mpdude** [comment]
Did not find any other problems in the meantime. Closing for now, thanks for your support!

**Comment by mnater** [comment]
Thank you!
