### ISSUE TITLE
not all words are broken on IE

### ISSUE THREAD

**Issue by selaru** [mnater/Hyphenator#302]
Hi,

We are using hyphenator on our site and we noticed that on IE 10+ (the other browsers are working well) not all the words are broken. 
The website is responsive and on a page we have a table with all the cells having widths in percentages (10%). When there are a minimum of 2 words in a cell, everything get broken correctly. But if we have only one word, it doesn't get broken at all and overlaps the cell on the right. 
I never used hyphenator before and was left with the js and css from another colleague which left the company.
I want at least some hints where to look and what options to play with.

Cheers,
Cristian

**Comment by mnater** [comment]
Hi,

Thanks for the report. I wasn't able to reproduce the issue. Could you please provide more details?
- Exact browser version
- OS Version
- Some html or a link where the problem occurs.

Thank you,
Mathias

**Comment by selaru** [comment]
Hi,

Browser: IE 11.0.96
OS: Windows 8.1 Enterprise
HTML:
`<div class="width-10">Ver­zend­huis­kre­diet</div>
<div class="width-10">Door­lo­pend kre­diet</div>`

CSS:
.width-10 {
    width: 10%;
}

These divs are cells in a table constructed with <ul> <li>. The first div won't hyphenate, the other one does. If i add another word in the first div, before or after, doesn't matter, then the hyphenate will work.
I also tried to hyphenate the word in console, as in the example page, with alert, and it did work. I guess it's something related to IE as in other browsers everything is ok.

Thanks,
Cristian

**Comment by mnater** [comment]
Still not able to reproduce. Here is my testcase http://mnater.github.io/Hyphenator/testsuite/test128.html based on your information.

Are there other (possibly inherited) CSS-properties on the `<div>`'s?
