### ISSUE TITLE
Publish latest version

### ISSUE THREAD

**Issue by mbrodala** [mnater/Hyphenator#303]
The latest release (5.1.0) is heavily outdated compared to the latest master:

https://github.com/mnater/Hyphenator/compare/5.1.0...master

Among others `leftmin` and `rightmin` cannot be used ATM.

Please publish the latest state as new release.

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenator/releases/tag/5.2.0

**Comment by mbrodala** [comment]
Thanks a lot. :-)

**Comment by mbrodala** [comment]
It seems like this version cannot be installed via NPM, I assume you need to update the `version` in your package.json:

`ERROR Module 'hyphenator.js@^5.2.0' not found`
