### ISSUE TITLE
Hyphenator 5.2.0 doesn't work at all (edit: issue with custom selector function)

### ISSUE THREAD

**Issue by jakubmarian** [mnater/Hyphenator#306]
There's something wrong with Hyphenator 5.2.0. Instead of hyphenating the text, it gives various error messages like "An Error occurred: lo.patternChars is undefined" in Firefox and "Cannot read property 'length' of undefined" in Chrome.

For some reason, this only happens when it is hosted on a public domain (e.g. [here](https://jakubmarian.com/Hyphenator-5.2.0/WorkingExample.html)). On localhost it works without any error messages.

**Comment by gusbemacbe** [comment]
Your link is broken.

**Comment by jakubmarian** [comment]
Sorry; it's fixed now.

**Comment by gusbemacbe** [comment]
I analysed your page on my mobile and desktop, and I didn't receive error message. Your page appeared normally hyphenated.

**Comment by jakubmarian** [comment]
I receive error messages on all my mobile devices and all desktop browsers (on mobile, the texts are hidden when the page is loaded for the first time, and the error messages appear on every reload).

**Comment by gusbemacbe** [comment]
I inspected your site and there's no error on the console. Strange. What is your Chrome and Firefox version now?

**Comment by jakubmarian** [comment]
The latest, Chrome 60.0.3112.113 and Firefox 55.0.2, but it does the same in older versions too, as well as in Internet Explorer and mobile browsers, so this does not seem to be in any way browser-specific.

[Here](https://jakubmarian.com/hyphenator.png)'s a screenshot of the error message.

**Comment by jakubmarian** [comment]
By the way, it's probably not a good idea to display errors as alerts by default. If something breaks, all visitors start getting these messages.

**Comment by jakubmarian** [comment]
Perhaps the following output will be helpful. It seems that the script does not catch the error when the page is opened in a freshly restarted browser window and gives the following output in the console:

> Uncaught TypeError: Cannot read property 'length' of undefined
>     at convertPatternsToArray (Hyphenator.js:1902)
>     at prepareLanguagesObj (Hyphenator.js:2128)
>     at Hyphenator.js:2156
>     at Array.forEach (<anonymous>)
>     at forEachKey (Hyphenator.js:325)
>     at languagesLoaded (Hyphenator.js:2150)
>     at HTMLScriptElement.script.onreadystatechange (Hyphenator.js:2046)

**Comment by gusbemacbe** [comment]
Which browsers versions did you receive these error message?

**Comment by jakubmarian** [comment]
The ones mentioned above (I don't remember the older version numbers). However, this is clearly not just some kind of browser incompatibility (I got error messages in every browser I tried so far, including several browsers on my phone and tablet).

**Comment by gusbemacbe** [comment]
> I got error messages in every browser I tried so far, including several browsers on my phone and tablet

Including Google Chrome 60 and Firefox 55?

Just a tip, drop the support for Internet Explorer, so the percent of users of Internet Explorer is decreasing, and if you insist in applying support for Internet Explorer, the users will continue to use very old and unsafe browser. Dropping it will encourage the users to migrate to the new and safe versions of browsers. The most of web designers, developers and programmers do not want to offer support for the eldest and unsafe browsers versions for not having much headache.

**Comment by jakubmarian** [comment]
> Including Google Chrome 60 and Firefox 55?

Yes, including more than 10 different browsers I tried. I think there must be an issue with pattern loading (something somewhere returns an empty result but shouldn't), but I don't understand how it can be broken in every browser for one person and work everywhere for another one.

P.S. I don't care much about IE support; I was just trying to show that the problem is not browser-specific.

**Comment by gusbemacbe** [comment]
When I'll be home, I'll check the codes lines of these error outputs.

**Comment by mnater** [comment]
Can't reproduce, either.
Strange.

Just an idea: maybe the pattern files where corrupted and are now in localStorage in a corrupted state… Clear localStorage in your browser(s) and try again.

**Comment by jakubmarian** [comment]
I asked three friends of mine to try the URL, and they are all getting the same results as me (blank spaces instead of texts and an error message on reload).

Are we really looking at the same thing? The URL is https://jakubmarian.com/Hyphenator-5.2.0/WorkingExample.html

**Comment by jakubmarian** [comment]
Ah, I just found out there was an error on my part; the files I uploaded already contained some modifications made by me through which I was trying to fix the issue. I have now uploaded the original, and the example started working for me (which, however, does not explain why the page worked for you but not for me and my friends).

Nevertheless, I am still getting the error messages when I include the minified version created by mergeAndPack on another page. I'll try to create a clean example and post it here as soon as possible.

**Comment by jakubmarian** [comment]
**I have been finally able to isolate the source of the errors!** I use a customized selector function in mergeAndPack.html (when you select _Custom: Collecting elements by a custom Selector-Function _).

The default selector function (the one you see when you select the aforementioned option in mergeAndPack) uses the variable contextWindow, which, apparently, is not accessible by the function, which caused the error. **Changing "contextWindow" to "window" fixes the issue.**

**Comment by gusbemacbe** [comment]
I am home, I was going to check, but you have already found what caused errors.

**Comment by jakubmarian** [comment]
Thanks for your help anyway. Even though the problem is not actually an issue with Hyphenator itself, the function you see when you click on "Custom: Collecting elements by a custom Selector-Function" in mergeAndPack.html should be fixed (when you use mergeAndPack.html to create a Hyphenator_Loader.js file and simply select "Custom: Collecting elements by a custom Selector-Function" without changing anything, the result is broken).

**Comment by mnater** [comment]
thank you
