### ISSUE TITLE
Hyphenator_Loader does not fire at certain zoom levels

### ISSUE THREAD

**Issue by jakubmarian** [mnater/Hyphenator#307]
Depending on the browser zoom level, shadow.offsetHeight in Hyphenator_Loader.js sometimes returns 11 and sometimes 12 (in both Chrome and Firefox on Windows), at least when the system-wide custom scaling factor in Display Settings (in Windows) is set to 120 (I didn't test other scaling factors).

Since the condition in the loader is **shadow.offsetHeight === 12**, hyphenator does not fire in those cases (the text is not hyphenated at some zoom levels). A simple way to fix this is to change the condition to **shadow.offsetHeight <= 13**, which should get rid of all rounding issues (I don't know whether there could be a similar problem with offsetHeight being one pixel bigger).

**Comment by mnater** [comment]
thank you
