### ISSUE TITLE
Weird issue with copying from child element of element with hyphenate class

### ISSUE THREAD

**Issue by Igor-Yavych** [mnater/Hyphenator#310]
Hello.
I've encountered this very weird issue.
Check [this](https://jsfiddle.net/exuw6yw1/2/) js fiddle 
As you can see, there are 2 `divs` - one with `hyphenate` and one with `donthyphenate`. Both of them have a child `p` tag and some text directly in them.
There is an event handler (just a simple one for the sake of a demonstration) for a `copy` event for these both `divs` and this is where weird thing happen. When you try to copy text from these 4 places, here what happens:
- all of the text -> works as expected 
- donthyphenate div > direct text -> works as expected 
- donthyphenate div > p -> works as expected 
- hyphenate div > direct text -> works as expected 
- hyphenate div > p -> doesn't work (doesn't work with any child element, not `p` specifically)
Option to remove hyphens on copying is off.
Version used is 5.2.0
Tried in different browsers
Any idea why this is happening and how to fix it?

**Comment by gusbemacbe** [comment]
Hey Igor,

Did you add hyphenate to `div `or `p`? Or did you add just to `html`?

**Comment by Igor-Yavych** [comment]
Hello, Gustavo. I've included jsfiddle link, https://jsfiddle.net/exuw6yw1/2/, in case you didn't see it above. It answers your question and demonstrates exactly where the problem is

**Comment by gusbemacbe** [comment]
Ah, you forgot of adding `en-us.js`.

**Comment by Igor-Yavych** [comment]
It doesn't matter in this case. Actual site has it where it should and this fiddle has it on div that's being hyphenated (it hyphenates it just fine btw). That's not really a problem.
Just try copying some part of text from each parts separately and you'll see the problem.

**Comment by gusbemacbe** [comment]
No, without pattern, it wouldn't work. Check my forked and updated JSFiddle: https://jsfiddle.net/8m4rgujc/1/

**Comment by gusbemacbe** [comment]
Apply `en-gb` instead of `en-us` and resize the window to smaller.

**Comment by Igor-Yavych** [comment]
You're completely missing my point here. It's not about it hyphenating text or not. It's about not it messing up other event handlers  on `copy` event. 
Try to copy part of the text from a paragraph under `Hyphenated div` and see that event handler for `copy` doesn't work. (In your case it is also true for `Hyphenated div` text itself, while in my fiddle on that part it works fine).

**Comment by gusbemacbe** [comment]
Are you meaning that if I add `test` to the `p` with `hyphenate` and copy the text, the alert won't pop up, right?

**Comment by gusbemacbe** [comment]
I mean only the paragraph text, right?

**Comment by Igor-Yavych** [comment]
You don't need to add anything. Just try to copy part of the text from a `p` child of a `div` with `hyphenate` class in my fiddle. You will not get an alert there. But if you try to copy a part of the text from either `Hyphenated div`, `Not hyphenated div` or its `p` child or all of the text in that fiddle together, you will get alert as expected.

**Comment by gusbemacbe** [comment]
* Without `test` in the `div` with `hyphenate`, selecting `Hyphenated div`, I copied and didn't get alerted.
* With `test` in the `div` with `hyphenate`, selecting `Hyphenated div` and whole `div`, I copied and got alerted.
* With `test` in the `div` with `hyphenate`, not selecting `Hyphenated div`, but selecting only `p`, I copied and didn't get alerted. [1]

* With `test` in the `div` with `donthyphenate`, selecting both `Not Hyphenated div` and `p`, I copied and got alerted.

* Selecting the whole text, I copied and I didn't get alerted. [2]

[1] Then have you already added `div > p` to the Javascript function of `.test`?
[2] You need to add `test` to the `hyphenate` class, then you will be alerted if you copy the whole text.

**Comment by Igor-Yavych** [comment]
I guess I'll just wait for @mnater to reply to me on this.

**Comment by mnater** [comment]
Hi @Igor-Yavych 

Thanks for reporting. I'm able to reproduce the issue and will look into it.

Just as a side note: you wrote "Option to remove hyphens on copying is off."
`safecopy` is on by default and you didn't turn it to false in the fiddle. With `safecopy: false` the copy event fires on all elements. But it should fire in both cases.
So it's definitely Hyphenator.js that messed something up…

**Comment by Igor-Yavych** [comment]
Hello, @mnater 
In the fiddle, yes, but I used http://mnater.github.io/Hyphenator/mergeAndPack.html to get it for the actual site and I had `Remove hyphenation when copying text Show-Info Button` unchecked. That's what I meant :)
Thanks, I appreciate you looking into it.

**Comment by mnater** [comment]
To work around issues with copying hyphenated text Hyphenator.js registers an oncopy-handler for each element to be hyphenated. Before the https://github.com/mnater/Hyphenator/commit/b436d0c1bf7ad0cb4510921024e0182bb3e9fd07 fix this handler stopped propagation of the copy event. That's why the alert didn't show up.

Thanks again for reporting, for the exact description and the jsfiddle.
Regards,
Mathias

**Comment by Igor-Yavych** [comment]
If I remove these 2 lines, selection disappears when I copy something. Not good. 
Try it https://jsfiddle.net/exuw6yw1/4/

**Comment by gusbemacbe** [comment]
in Your updated JSFiddle, here everything worked.

**Comment by mnater** [comment]
No, not good at all.
This is going to be very complicated:
When stopPropagation is removed the event fires on the inner p and the outer div. The shadow-element gets inserted two times and the restoring of the selection range is troubled (at its very bad for perf).
I should make sure that the copy-event is only registered for outer elements.
This needs more work to be done…
(I don't like this safecopy-hack at all)

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenator/releases/tag/5.3.0

**Comment by Igor-Yavych** [comment]
Many thanks. Can confirm, working well.
