### ISSUE TITLE
getBasePath Failed in IE if Hyphenator is merged with other scripts

### ISSUE THREAD

**Issue by revoltek-daniel** [mnater/Hyphenator#311]
If you merge Hyphenator with other scripts, to get one minified script, loading failed in IE.

`Unable to get property 'substring' of undefined or null reference` in https://github.com/mnater/Hyphenator/blob/fa43f574d066212e21b16aa820e2cdc00803e6c0/Hyphenator.js#L154

If running in IE document.currentScript is not supported so https://github.com/mnater/Hyphenator/blob/cf767cd5e957d782a7840847e75ce9a61d8b6fd0/Hyphenator.js#L159 is triggered, but this method can't find a script named Hyphenator cause it is merged to another file.

**Comment by revoltek-daniel** [comment]
If I see it correct in master branch its fixed, is there any plan for a new release so we could use it?

**Comment by mnater** [comment]
Hi

Yes, this was fixed in https://github.com/mnater/Hyphenator/pull/308
New release by end of the week…

Regards,
Mathias

**Comment by mnater** [comment]
https://github.com/mnater/Hyphenator/releases/tag/5.3.0
